---
name: neighbormodels
channels:
  - defaults
  - conda-forge
  - matsci
dependencies:
  - click=6.7
  - cython=0.28.4
  - enumlib=1.0.4
  - flask=1.0.2
  - ipython=6.5.0
  - itsdangerous=0.24
  - jedi=0.12.1
  - jinja2=2.10
  - jupyter=1.0.0
  - markupsafe=1.0
  - matplotlib=2.2.2
  - networkx=2.1
  - nose=1.3.7
  - numpy=1.15.0
  - numpy-base=1.15.0
  - pandas=0.23.3
  - pydispatcher=2.0.5
  - python=3.7.0
  - pyyaml=3.13
  - requests=2.19.1
  - ruamel_yaml=0.15.42
  - scipy=1.1.0
  - six=1.11.0
  - sphinx=1.7.6
  - sympy=1.2
  - tabulate=0.8.2
  - werkzeug=0.14.1
  - pip:
      - ase==3.16.2
      - autopep8==1.3.5
      - flake8==3.5.0
      - monty==1.0.3
      - pybtex==0.21
      - pycodestyle==2.3.1
      - PyHamcrest==1.9.0
      - pymatgen==2018.7.23
      - pytest==3.7.0
      - rope==0.10.7
      - yapf==0.22.0
...
